I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/options.rpy", line 88, in script
    define config.after_load_transition = Nodissne
  File "game/options.rpy", line 88, in <module>
    define config.after_load_transition = Nodissne
NameError: name 'Nodissne' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/options.rpy", line 88, in script
    define config.after_load_transition = Nodissne
  File "D:\L0veRavenRenPy\- RenPy\renpy\ast.py", line 2241, in execute
    self.set()
  File "D:\L0veRavenRenPy\- RenPy\renpy\ast.py", line 2255, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "D:\L0veRavenRenPy\- RenPy\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/options.rpy", line 88, in <module>
    define config.after_load_transition = Nodissne
NameError: name 'Nodissne' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
My Love 1.0
Wed Jul 30 11:53:24 2025
