I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
  File "renpy/common/00start.rpy", line 83, in _init_language
    renpy.change_language(language)
  File "game/screens.rpy", line 138, in <module>
    background Color("gui/textbox.png", xalign=0.5, yalign=1.0)
TypeError: __new__() got an unexpected keyword argument 'xalign'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\renpy-8.3.4-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "D:\renpy-8.3.4-sdk\renpy\main.py", line 652, in main
    run(restart)
  File "D:\renpy-8.3.4-sdk\renpy\main.py", line 75, in run
    renpy.translation.init_translation()
  File "D:\renpy-8.3.4-sdk\renpy\translation\__init__.py", line 702, in init_translation
    renpy.store._init_language() # type: ignore
  File "renpy/common/00start.rpy", line 83, in _init_language
    renpy.change_language(language)
  File "D:\renpy-8.3.4-sdk\renpy\translation\__init__.py", line 796, in change_language
    new_change_language(tl, language)
  File "D:\renpy-8.3.4-sdk\renpy\translation\__init__.py", line 748, in new_change_language
    i.apply()
  File "D:\renpy-8.3.4-sdk\renpy\ast.py", line 2806, in apply
    value = renpy.python.py_eval(expr)
  File "D:\renpy-8.3.4-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\renpy-8.3.4-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/screens.rpy", line 138, in <module>
    background Color("gui/textbox.png", xalign=0.5, yalign=1.0)
TypeError: __new__() got an unexpected keyword argument 'xalign'

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
My Love 1.0
Thu Jul 24 13:42:45 2025
